### PR TITLE
GHC 9 support

### PR DESCRIPTION
**Pull request by sorki**
Relaxes `base` bounds, bumps `typerep-map` and `polysemy`.

### CODE REVIEW

**Review by vrom911 — COMMENTED** [review]
Hey @sorki ,

Thanks a lot for this update! Looks nice!
Could you please also add `9.0` into the GitHub Actions file, so we could have a check on CI that everything is still good?

**Comment by sorki** [comment]
Sure, added! I think it's going to get cancelled due to some unrelated fail in older one(s) but lets see.

**Comment by sorki** [comment]
All green now.

**Review by chshersh — APPROVED** [review]
Thanks! Looks neat 🙂

**Review by vrom911 — APPROVED** [review]
Thanks!

**Comment by chshersh** [comment]
@alaendle FYI, [`co-log-polysemy-0.0.1.3`](https://hackage.haskell.org/package/co-log-polysemy-0.0.1.3) has been released to Hackage with GHC 9.0 support.

**Comment by alaendle** [comment]
@chshersh Many thanks for the hint, unfortunately my project not only depends in `co-log-polysemy`, but only on `co-log` - so since their latest releases on hackage differ in the version dependency on `co-log-core` ((>=0.3.0.0 && <0.4) vs. (>=0.2.1.0 && <0.3)) I'm still using the git repository

```yaml
extra-deps:
- git: https://github.com/co-log/co-log.git
  commit: 72fbe394b437c698d574cd7604ad3f7f807383e0
  subdirs:
    - co-log
    - co-log-core
    - co-log-polysemy
```
for now. This is only for explanation and if someone experiences a similar problem and in absolute no way criticism! I really appreciate your work and the design of the `co-log` library in particular 👍 .

**Pull request merged**
